version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    # ports:
    #   - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - orderservice
      - userservice

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: src/OrderService/OrderService.API/Dockerfile
    # ports:
    #   - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: src/UserService/UserService.API/Dockerfile
    # ports:
    #   - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

