version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: ./src/OrderService/OrderService.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: ./src/UserService/UserService.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

  notificationservice:
    image: notificationservice:latest
    build:
      context: ./src/NotificationService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - orderservice
      - userservice
