services:
  rabbitmq:
    image: rabbitmq:3-management
    # ports:
    #   - '5672:5672'
    #   - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: src/OrderService/OrderService.API/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: src/UserService/UserService.API/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    depends_on:
      - orderservice
      - userservice
    restart: on-failure
